site_name: CineVault
site_description: Automate and secure your home infrastructure with a declarative, zero-trust container stack.
site_url: https://MelvinLoos.github.io/CineVault/
repo_url: https://github.com/MelvinLoos/cinevault
repo_name: MelvinLoos/cinevault

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: cyan
      accent: cyan
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Deployment:
      - Initial Setup: deployment/initial-setup.md
      - Setting up the host: deployment/bare-metal-provisioning.md
  - Configuration:
      - Homepage Dashboard: configuration/homepage.md
      - Spotweb Integration: configuration/spotweb.md
      - Wizarr Onboarding: configuration/wizarr.md
      - Tdarr Transcoding: configuration/tdarr.md
      - Bazarr Configuration: configuration/bazarr.md
  - Maintenance:
      - Storage Cleanup: maintenance/storage-cleanup.md
